
[tool.poetry]
name = "harp"
version = "2.0.3"
description = "Harmonized Ancillary Resource Provider"
authors = [
      "Joackim Orcière",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]

exclude = [
    "misc",
    "__pycache__",
    "*__pycache__*",
]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.18.0"
netcdf4 = "*"
h5netcdf = "*"
xarray = "*"
# dask = "*"
h5py = "*"

core = {git = "https://github.com/hygeos/core.git"}

pydap  = "3.5"
pandas = "*"
cdsapi = ">=0.7.5"
scipy  = "*"
lxml   = "*"

[tool.poetry.scripts]
harp = "harp.cli:entry"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-html = "*"
pytest-xdist = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
